name: Build Using System LLVM
on:
  pull_request:
  schedule:
    - cron:  '0 15 * * 0'

jobs:
  build-on-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15
          sudo apt-get -y install libllvm15 llvm-15 llvm-15-dev llvm-15-runtime clang-15 clang-tools-15 libclang-common-15-dev libclang-15-dev libclang1-15 libomp-15-dev libmlir-15-dev
      - run: |
          cd oclint-scripts
          ./build -no-ninja -llvm-root=/usr/lib/llvm-15
          ./bundle -archive -llvm-root=/usr/lib/llvm-15
  build-on-mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer
          brew update
          brew install llvm@15
      - run: |
          cd oclint-scripts
          ./build -no-ninja -llvm-root=/usr/local/opt/llvm\@15
          ./bundle -archive -llvm-root=/usr/local/opt/llvm\@15
